Created FontResources and changed the PDFWithTimeNewRomanText.java to…
A-Cain/Group-6-PDFBox_project pull request #25
Opened 2021-04-22 22:41 UTC by Nerd1000percent

Created Test for the Multi font function.

2021-04-22 22:45 UTC, Nerd1000percent commented
The subject name is wrong

2021-04-22 22:54 UTC, A-Cain requested changes
Firstly: pressing 2 for courier gives me a pdf that reads "This Text is in Times New Roman"
While I can tell it is in courier, it is still misleading.

Also, having to run the test twice to test both fonts is somewhat laborious for a test. It would be ideal if it either produced one pdf with both fonts present, or one pdf for each font. The first would best demonstrate the desired capability. 

Finally the test is not in junit format and thus will not run when a "run all tests" is called in the development environment. For the sake of continuity with other tests, I would ask that it be in junit format

2021-04-22 23:03 UTC, Nerd1000percent commented
I have made the first 2 changes, not sure how to make a junit though.

2021-04-22 23:06 UTC, A-Cain commented
> I have made the first 2 changes, not sure how to make a junit though.

the function that contains the test code should have 
@Test
in the line above it, and should be titled something like TestMultiFont or something similar. It should also end by asserting that each (or the one) created test file exists. There should be a comment telling reviewers that they need to manually look at the created test file to verify proper font use

2021-04-22 23:11 UTC, Nerd1000percent commented
Awesome THANKS, I think its good now.

2021-04-22 23:12 UTC, A-Cain requested changes

2021-04-22 23:12 UTC, A-Cain commented on tools/src/test/java/org/apache/pdfbox/tools/MultiFontTest.java
The test function should not be public static void main

2021-04-22 23:13 UTC, A-Cain commented
Here is an example of one of my tests:

@Test
    public void testMain() throws IOException {
        AddImage add = new AddImage();
        add.loadFileandInitializeStream("../tools/src/main/java/org/apache/pdfbox/tools/AddImageResources/examplePDFWithText.pdf", 2);
        String imageString = "../tools/src/main/java/org/apache/pdfbox/tools/AddImageResources/pamcamke.jpg";
        PDImageXObject actual = add.createImage(imageString);
        add.writeImage("../tools/src/main/java/org/apache/pdfbox/tools/AddImageResources/examplePDFWithTextAndImage.pdf");
        File madeFile = new File("../tools/src/main/java/org/apache/pdfbox/tools/AddImageResources/examplePDFWithTextAndImage.pdf");
        assertTrue(madeFile.exists());
    }

note that it is not a main function, and that ti ends by asserting something that junit can use to determine a pass or fail

2021-04-22 23:35 UTC, Nerd1000percent commented
Ok I see, I had to import that juint it wasn't working until I found the exact assert. I think its good now maybe.

2021-04-22 23:39 UTC, A-Cain commented
Does the test pass on your machine? As of now it does not on mine because the file Courier.pdf is not created

2021-04-22 23:40 UTC, Nerd1000percent commented
I see why,

2021-04-23 01:05 UTC, A-Cain commented
Let me know when the issue is fixed and I will merge the request

2021-04-23 17:36 UTC, Nerd1000percent commented
Ok I made some changes and it passes now.

2021-04-23 17:38 UTC, A-Cain commented
I will tryst you that it works.

2021-04-23 17:38 UTC, merged